# deploy cursed mage build to ubuntu box
name: Deploy Cursed Mage

# actions will run on manual trigger
on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy Cursed Mage'
        required: false

# jobs to run
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
        
      - name: Install Poetry
        run: |
          (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python - 

      - name: Install Dependencies
        run: |
          $env:PATH += ";$env:USERPROFILE\AppData\Roaming\Python\Scripts"
          poetry install

      - name: Build application
        run: |
          $env:PATH += ";$env:USERPROFILE\AppData\Roaming\Python\Scripts"
          poetry run pyinstaller build.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: CursedMage.exe
          path: dist/CursedMage.exe

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: CursedMage.exe
          path: .

      - name: Copy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: CursedMage.exe
          target: /www/public/dist/CursedMage.exe