# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

# install dependencies, run tests, and if successful build and publish
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: install dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest
      - name: build with pyinstaller
        run: poetry run pyinstaller build.spec
      - name: publish to github releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}